### ISSUE TITLE
Add a glossary

### ISSUE THREAD

**Issue by widhalmt** [binford2k/showoff#227]
Hi!

I would like to have a glossary of some kind with automatic links to descriptions. I could imagine different implementations:
- A standalone file with a definition list of pairs of phrase and definition
- Another way, easier for author but supposedly harder to implement, would be to add a way the definitions could added in the slides themselves like alternative text for images

The glossary could be reached by `/glossary` like `/onepage` . An extra benefit would be if words that are defined in the glossary get linked to the definitions when they are used in the slides. Alternatively it could be shown when students hover over the word in the presentation.

It should be part of the pdf and `/print` output, too. Either as a standalone section or as footnotes.

A totally different approach is the glossary module for the Drupal CMS. I'm just linking it here to clarify what I mean: https://www.drupal.org/project/glossary

Kind regards,
Thomas

**Comment by binford2k** [comment]
Hey Thomas!

You can build a manual glossary right now with not too much work using named links. The slide using the term would have links, something like:

``` Markdown
<!SLIDE>
# This is a slide

It uses some terms like [this one](#conclusion/glossary) and this
[other one](#conclusion/glossary) that are defined at the end of
the presentation in the glossary.
```

Then the glossary slide, `conclusion/glossary.md`, would have a js link, like

``` Markdown
<!SLIDE>
# Glossary

* this one
    * a definition
* other one
    * another definition

[Return to slide](javascript:history.go(-1))
```

I'll leave the ticket open though, because this is a useful idea. At some point, I'd like to have footnotes, endnotes, glossary items, all.
