### ISSUE TITLE
Zoom factor isn't maintained when a window is resized.

### ISSUE THREAD

**Issue by natemccurdy** [binford2k/showoff#229]
After pressing the "Next Window" button, a new window pops up with the next slide it in scaled down to fit the small window size. When resizing that window, the content zooms in to match the scale of the presenter view.

The content of the "Next Window" should scale to the window's dimensions during resize.

**Comment by natemccurdy** [comment]
One way around this is to use a browser that can zoom in/out _per_ window. I've found that Safari for OSX can while Chrome for OSX can't.

tl;dr - Use Safari.

**Comment by binford2k** [comment]
oh that's.... odd. That would explain why I didn't completely know what you meant! I'll still see if there's anything I can do.

**Comment by binford2k** [comment]
Ok, had time to get back and look at this. So what's actually going on is that the window reloads on size change because a handful of things have dynamically calculated sizes. The problem there is that the zoom factor isn't maintained :/

The real fix is that I need to make the onload size calculations dynamic so that they recalculate on windows resize rather than just sledgehammer reloading the entire window.
