### ISSUE TITLE
Replace "Slave Window" with something less fraught.

### ISSUE THREAD

**Issue by big-samantha** [binford2k/showoff#253]
Currently, to open a second window for presenting, you click a button labeled "Slave Window". The word "Slave" is sort of fraught, and I'm sure we could come up with something better.

E.g. perhaps "Presenting Window" or something like that.

**Comment by binford2k** [comment]
Heh. This is the third time this conversation has come up in three years. None of the conversations came up with a better name that didn't overload other names. We're already using "presenter view" so "presenting window" is out because it's too similar and confusing. "Follower" is another, but I'm using that to indicate that the presenter can be driven from multiple devices (like your phone).

Come up with a better name or set of names that's recognized in the industry like [master/slave](http://en.wikipedia.org/wiki/Master/slave_%28technology%29), and I'd be happy to change. Maybe "Display view"?

**Comment by binford2k** [comment]
@brookshelley hey, you got opinions?

**Comment by klynton** [comment]
:+1: to Display view or Display window.

**Comment by big-samantha** [comment]
"Display View" is okay.

"Projector View" wouldn't be bad either - doesn't matter if there's no actual projector (like it's a big TV or something), it'll still be obvious what it is.

> that's recognized in the industry like master/slave

This argument doesn't hold any weight with me. It's pretty unacceptable regardless of industry recognition. It's easy enough to tell people what the button does. The buttons all have pop-up explanations anyway.

**Comment by binford2k** [comment]
The audience is much larger than just our PSEs.

**Comment by Sharpie** [comment]
"Screen View"? But that is close enough to "Display View" that the two are pretty interchangeable.

**Comment by brookshelley** [comment]
Agent view? Secondary screen? Additonal Screen/view?

**Comment by brookshelley** [comment]
Child window

**Comment by brookshelley** [comment]
Spawn a child window :)

**Comment by big-samantha** [comment]
+1 to Child Window, with a pop-up explanation saying what that means.
