### ISSUE TITLE
Applying template to presentation leads to uncompiled markdown in slides

### ISSUE THREAD

**Issue by marcelhuth** [binford2k/showoff#381]
Hi,

I tried to get my own Showoff theme running. As soon as I apply the template slide's content is the base markdown content only. There is no translation from markdown to HTML anymore.

Here is the "theme" (made it very very basic for testing ;) )

```
<div class="themedefault">
  ~~~CONTENT~~~
</div>
```

And the corresponding CSS (very basic as well)

```
.themedefault {
    position: absolute;
    width: 100%;
    height: 100%;
}
```

As soon as the template is applied to presentation everything on the slide is the basic markdown file content for that slide. There should be a translation to HTML (what works, when not applying the template).

Does anybody has an idea what goes wrong here? Did I forget anything?

Thanks,

/Marcel

**Comment by binford2k** [comment]
Yes. The markdown renderer shuts itself off within `<div>` tags. It expects that you'll be writing HTML inside the div. I don't know why this is a thing, and I haven't tried to change it yet. The net result is that you cannot wrap sides in divs.

Luckily, you probably don't have to. Instead of putting styles on `.themedefault`, you can just apply those styles to `.slide` and get the look you're going for. You can also style individual slide classes. Slides defined like `<!SLIDE section default emphasis>` will have the classes of `section`, `default`, `emphasis` applied as well.

We are in the process of a major style overhaul and plan to include a styling guide with it. It will be released before the end of February.
