### ISSUE TITLE
Presenter options should have less chrome

### ISSUE THREAD

**Issue by binford2k** [binford2k/showoff#623]
The presenter options currently have checkboxes for enable/disable. They should instead use something like https://jqueryui.com/checkboxradio/#no-icons to make the UI less messy and lower the cognitive weight of using them.

**Comment by slambert** [comment]
I've had some thoughts about further refining the presenter view. Are there other thoughts/plans floating around?

**Comment by binford2k** [comment]
I'll be cutting a `.Y` release within days that allows the user to hide the sidebar and resize or pop out the notes pane. Along with the layout options that came in `v0.15`, the mechanics of the thing should be getting pretty solid.

What other ideas are you bouncing around?

**Comment by slambert** [comment]
I can't commit time to it in the near future, but I dream of...

**Updating the design itself** - more flat, less dropshadows
**Darkening the design** - more dark backgrounds and white text – less of a blinding bright laptop screen for the presenter. 

I liked what you were saying above about lowering cognitive weight. To that end, maybe working with [graphs like this](https://blogs.adobe.com/creativecloud/css-vs-svg-the-final-roundup/) or [this circular graph font](http://www.macosxtips.co.uk/geeklets/system/system-info-circular-graphics/) to show pace side by side or overlaid with the timer. Toward the same end, perhaps making slide count & percentage more graphical.

**Make presenter notes more readable for the presenter**
1) move the presenter notes to the top of the screen instead of the bottom, so the speaker looks down less to glance at notes. (The image of the slide itself should be familiar and can be scanned quickly, but the notes may require a closer read. If they're at the top of the screen, the presenter seems less like they're burying they're head in their laptop.)
2) Make the presenter notes larger - or make the layout so that if you increase the font size in the browser, on that page it only increases the size of the presenter notes. Or some other way if increasing font size (maybe something similar to bigtext?) so it's as large as possible in that space.

These are dreams....

**Comment by slambert** [comment]
Another thought - style the presenter view using the css from the slideshow using css `@import`?  Even more possible with the move toward `vw`/`vh` sizes.

Let me know if I'm moving out of _dream_ territory into a _hallucination zone_.

**Comment by binford2k** [comment]
I don't think it's a good idea to style the presenter view with presentation-modifiable css. That seems too easy to break things! I'll think on it though. (to be clear, you already *can* do that, albeit with a bit of unsupported poking)

**Comment by slambert** [comment]
@binford2k Sorry, I could have phrased that last one better. I was meaning that the slide previews in the presentation could match the style of the presentation. So your preview better matches what's on screen.

So, for example, today I was making a slideshow that was a black background with white text and using a webfont I had locally. Those styles don't appear in the slide previews in presenter view - that view is black on white with the default font.

Does that make more sense?
