### ISSUE TITLE
Pause slideshow does not replicate on regular/Display connections?

### ISSUE THREAD

**Issue by dafydd2277** [binford2k/showoff#875]
If I press "P" in the Presenter (http://localhost:9090:/presenter) window and enter an integer, I get the slide show in the preview pane of the Presenter window. However, the slide show is not duplicated in any Display (http://localhost:9090:/) windows. The "Display Window" menu item at the top of the Presenter window will give me a new Display window, which also won't duplicate the slide show. So, so far, the only place the slide show appears is in the Presenter Preview pane.

The documentation is unclear on whether or not the slideshow should appear on Display windows. It should, though, as a Display window seems to be what goes up on the projector during a presentation.

Thanks!

**Comment by binford2k** [comment]
That means that instead of opening a Display Window to put on the projector, you've just opened another tab/window and loaded the page manually. When you do that, it behaves as though that second window is an audience member, not a presenter. Current versions will provide a warning when you do this in most cases:
<img width="710" alt="screen shot 2018-11-17 at 4 08 00 pm" src="https://user-images.githubusercontent.com/1392917/48667069-fc0a9480-ea82-11e8-9465-d318c160a221.png">

The solution? Close that window and click the *Display Window* button to open it properly. If that still gives you issues, then reopen this ticket and explain exactly how you're opening and positioning your windows. (If you know how, you can open the Web Inspector on the Display Window and report back the values of the variables `presenter` and `presenterView`.)
